AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Role: arn:aws:iam::123456789012:role/execution_role
      Code:
        S3Bucket: my-bucket
        S3Key: lambda-function-code.zip
      Runtime: python3.8
      Timeout: 60
      MemorySize: 128

  MyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: MyAPI
